### ISSUE TITLE
As an user I want to see what bet I have placed using discord command 

### ISSUE THREAD

**Issue by xTomsko** [TheMuppet/DAYO#15]
Additional info:

**Comment by xTomsko** [comment]
@TheMuppet @Lesoge @alexsc23 

Can you please confirm, if the representation is sufficient enough?

```
Match 1: Man ❤️ Woman
Match 2: Man ❤️ Woman
Match 3: Man ❤️ Woman
Match 4: Man ❤️ Woman
Match 5: Man ❤️ Woman
Match 6: Man ❤️ Woman
Match 7: Man ❤️ Woman
Match 8: Man ❤️ Woman
Match 9: Man ❤️ Woman
Match 10: Man ❤️ Woman
```

**Comment by TheMuppet** [comment]
I'm not sure what you mean, but an 11th person is added during the show.

**Comment by xTomsko** [comment]
I know but only ten matches remain, don't they. I am only asking if this is enough as a response on the command to see what you have bet.? 

I guess I will add a short text like "Your bet:"
