### ISSUE TITLE
Deno Action performs Deno fmt check on dist folder with bundled javascript

### ISSUE THREAD

**Issue by xTomsko** [TheMuppet/DAYO#20]
Additional info:
The dist directory is serving the frontend and has bundled javascript. Deno action will always fail because of this file and make the action therefore obsolete. We should investigate and find a solution to exclude dist from the action

**Comment by alexsc23** [comment]
https://deno.land/manual/tools/formatter#ignoring-code

**Comment by alexsc23** [comment]
Fixed problem by adding deno config file. See pr #19
https://deno.land/manual/getting_started/configuration_file.md
