### ISSUE TITLE
Implement CI/CD

### ISSUE THREAD

**Issue by xTomsko** [TheMuppet/DAYO#5]

**Comment by TheMuppet** [comment]
Heroku App Created
Added basic Deno Action

**Comment by xTomsko** [comment]
(For docu, was already added earlier)

Added CodeQL standard tests
Added Deepsource

**Comment by xTomsko** [comment]
Created discord Heroku app with Continuous Deployment

**Comment by xTomsko** [comment]
added build yml for frontend bundling, added Procfile to host website on Heroku.

**Comment by xTomsko** [comment]
CI/CD complete
